### PR TITLE
patch mold-source-map

### PR DESCRIPTION
**Pull request by huayang-codaio**
https://staging.coda.io/d/Quality-Tracker_d-GJF-DmEUK/Bugs_sucBW#Bugs_tuq-W/r20768&modal=true

to be used by packs-sdk PR https://github.com/coda/packs-sdk/pull/1689

### CODE REVIEW

**Review by jonathan-codaio — APPROVED** [review]
Sure, worth a shot I guess

**Comment by jonathan-codaio** [comment]
Actually give my realization in https://github.com/coda/packs-sdk/pull/1690#pullrequestreview-845986751 that Lambda runs on node 14, should we keep all of these on 14?

**Comment by huayang-codaio** [comment]
@jonathan-codaio oh, good point. but pack developers may run in NodeJs16. Maybe we should add into the tutorial to ask them to run in Node14? In that case the deprecation warning isn't an issue. hahah

**Comment by jonathan-codaio** [comment]
> @jonathan-codaio oh, good point. but pack developers may run in NodeJs16. Maybe we should add into the tutorial to ask them to run in Node14? In that case the deprecation warning isn't an issue. hahah

I think it's worth pointing out that execution environment is currently Node 14 so we recommend using that for consistency, defer to @ekoleda-codaio on how to handle that and how strongly to suggest that to developers.

I'm guessing that most people are both lazy and don't understand the difference so will just use whatever node version is already installed as long as it doesn't trigger incompatibility errors.

**Comment by huayang-codaio** [comment]
let me revert back to NodeJs14.

**Comment by huayang-codaio** [comment]
actually I realized that the patch is dependent on node versions.. I need to fix the packs-sdk coda init.

**Comment by huayang-codaio** [comment]
I gave up this one. tried best to align my local node/npm version with the CI but still can't have the patch applied. 

It's not a big deal now since I am making packs-sdk CLI to create the patch.

**Pull request closed without merging**
